const locations = [
  "Library",
  "Coffee shop",
  "Park",
  "Bookstore",
  "Cafe",
  "Home office",
  "Writing studio",
  "Co-working space",
  "Hotel lobby",
  "Airport lounge",
  "Train station",
  "Bus stop",
  "Barber shop",
  "Beauty salon",
  "Day spa",
  "Gym",
  "Yoga studio",
  "Meditation room",
  "Park bench",
  "Picnic table",
  "Beach",
  "Lakefront",
  "Riverfront",
  "Mountain trail",
  "Forest",
  "Garden",
  "Museum",
  "Art gallery",
  "Theater",
  "Music venue",
  "Movie theater",
  "TV studio",
  "Radio station",
  "Recording studio",
  "Library",
  "Archive",
  "Antique shop",
  "Flea market",
  "Thrift store",
  "Consignment shop",
  "Supermarket",
  "Convenience store",
  "Gas station",
  "Pharmacy",
  "Department store",
  "Shopping mall",
  "Clothing store",
  "Footwear store",
  "Jewelry store",
  "Gift shop",
  "Toy store",
  "Electronics store",
  "Home goods store",
  "Furniture store",
  "Hardware store",
  "Gardening store",
  "Pet store",
  "Bookstore",
  "Office supply store",
  "Stationery store",
  "Art supply store",
  "Camera store",
  "Music store",
  "Video game store",
  "Sports store",
  "Outdoor equipment store",
  "Fishing and hunting store",
  "Camping store",
  "Auto parts store",
  "Tire store",
  "Service station",
  "Car wash",
  "Detailing shop",
  "Locksmith",
  "Shoe repair",
  "Tailor",
  "Dry cleaner",
  "Laundromat",
  "Storage facility",
  "Moving company",
  "Post office",
  "Bank",
  "Credit union",
  "Investment firm",
  "Financial advisor",
  "Insurance agency",
  "Law office",
  "Medical office",
  "Dentist office",
  "Chiropractor office",
  "Physical therapy clinic",
  "Massage therapist office",
  "Acupuncture clinic",
  "Naturopathic clinic",
  "Mental health clinic",
  "Addiction treatment center",
  "Hospice care facility",
  "Assisted living facility",
  "Nursing home",
  "Hospitals"
];

const characters = [
  "Wrestler",
  "Baker",
  "Priest",
  "Teacher",
  "Student",
  "Nurse",
  "Doctor",
  "Lawyer",
  "Engineer",
  "Artist",
  "Musician",
  "Athlete",
  "Chef",
  "Dancer",
  "Photographer",
  "Journalist",
  "Author",
  "Poet",
  "Actor",
  "Actress",
  "Model",
  "Fashion designer",
  "Makeup artist",
  "Hairdresser",
  "Barber",
  "Personal trainer",
  "Yoga instructor",
  "Meditation teacher",
  "Life coach",
  "Therapist",
  "Counselor",
  "Social worker",
  "Psychologist",
  "Psychiatrist",
  "Police officer",
  "Firefighter",
  "EMT",
  "Paramedic",
  "Soldier",
  "Marine",
  "Navy SEAL",
  "Airman",
  "Astronaut",
  "Pilot",
  "Co-pilot",
  "Flight attendant",
  "Air traffic controller",
  "Ground crew",
  "Dispatcher",
  "Mechanic",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Construction worker",
  "Architect",
  "Urban planner",
  "Landscape architect",
  "Environmentalist",
  "Zookeeper",
  "Veterinarian",
  "Marine biologist",
  "Astronomer",
  "Geologist",
  "Meteorologist",
  "Chemist",
  "Physicist",
  "Mathematician",
  "Statistician",
  "Computer scientist",
  "Software developer",
  "Web developer",
  "Database administrator",
  "Network administrator",
  "IT support",
  "Cybersecurity analyst",
  "Data scientist",
  "Business analyst",
  "Economist",
  "Accountant",
  "Financial analyst",
  "Investment banker",
  "Real estate agent",
  "Insurance agent",
  "Stockbroker",
  "Marketing analyst",
  "Public relations specialist",
  "Advertising executive",
  "Event planner",
  "Travel agent",
  "Tour guide",
  "Hotel manager",
  "Airbnb host",
  "Uber driver",
  "Taxi driver",
  "Postal worker",
  "Courier",
  "Package delivery driver",
  "Truck driver",
  "Bus driver",
  "Train conductor",
  "Subway operator",
  "Ferry operator",
  "Longshoreman",
  "Dockworker",
  "Customs agent",
  "Border patrol agent",
  "FBI agent",
  "CIA agent",
  "Secret service agent",
  "NSA agent",
  "Homeland security agent"
]

const objects = [
  "Key",
  "Wallet",
  "Phone",
  "Computer",
  "Tablet",
  "Camera",
  "Watch",
  "Bracelet",
  "Necklace",
  "Ring",
  "Earring",
  "Laptop",
  "Table",
  "Chair",
  "Couch",
  "Bed",
  "Blanket",
  "Pillow",
  "Sheet",
  "Comforter",
  "Towel",
  "Rug",
  "Carpet",
  "Curtain",
  "Blind",
  "Shade",
  "Lamp",
  "Lightbulb",
  "Battery",
  "Charger",
  "Adaptor",
  "Headphones",
  "Speakers",
  "Microphone",
  "Webcam",
  "Printer",
  "Scanner",
  "Fax machine",
  "Copier",
  "Stapler",
  "Paper clip",
  "Tape",
  "Glue",
  "Scissors",
  "Ruler",
  "Compass",
  "Protractor",
  "Calculator",
  "Clock",
  "Thermometer",
  "Barometer",
  "Hygrometer",
  "Weather station",
  "Fire extinguisher",
  "Smoke detector",
  "Carbon monoxide detector",
  "Flashlight",
  "Candle",
  "Matches",
  "Lighter",
  "Grill",
  "Barbecue",
  "Frying pan",
  "Pot",
  "Pan",
  "Bowl",
  "Plate",
  "Cup",
  "Mug",
  "Glass",
  "Bottle",
  "Can",
  "Jar",
  "Bag",
  "Backpack",
  "Suitcase",
  "Luggage",
  "Umbrella",
  "Bicycle",
  "Skateboard",
  "Scooter",
  "Surfboard",
  "Snowboard",
  "Ski",
  "Helmet",
  "Goggles",
  "Sunglasses",
  "Hat",
  "Cap",
  "Beanie",
  "Scarf",
  "Gloves",
  "Mittens",
  "Coat",
  "Jacket",
  "Sweater",
  "Shirt",
  "T-shirt",
  "Pants",
  "Jeans",
  "Shorts",
  "Skirt",
  "Dress",
  "Suit",
  "Tie",
  "Belt",
  "Shoe",
  "Sneaker",
  "Boot",
  "Sandals",
  "Slippers",
  "Flip flops",
  "High heels"
]

const scenarios = [
  "At a job interview",
  "At a wedding",
  "At a funeral",
  "At a party",
  "At a concert",
  "At a sporting event",
  "At a political rally",
  "At a religious ceremony",
  "At a business meeting",
  "At a conference",
  "At a job fair",
  "At a college fair",
  "At a networking event",
  "At a class reunion",
  "At a family reunion",
  "At a baby shower",
  "At a bridal shower",
  "At a bachelor/bachelorette party",
  "At a picnic",
  "At a barbecue",
  "At a potluck",
  "At a cookout",
  "At a dinner party",
  "At a formal event",
  "At a club",
  "At a bar",
  "At a lounge",
  "At a casino",
  "At a bowling alley",
  "At a skating rink",
  "At a movie theater",
  "At a comedy club",
  "At a theater",
  "At a dance club",
  "At a karaoke bar",
  "At a pool hall",
  "At a gym",
  "At a yoga class",
  "At a martial arts class",
  "At a dance class",
  "At a cooking class",
  "At a painting class",
  "At a pottery class",
  "At a photography class",
  "At a writing class",
  "At a book club",
  "At a game night",
  "At a board game cafe",
  "At a video game tournament",
  "At a card game tournament",
  "At a chess club",
  "At a miniature golf course",
  "At a go-kart track",
  "At a rock climbing gym",
  "At a trampoline park",
  "At a laser tag arena",
  "At a bowling alley",
  "At a batting cage",
  "At a driving range",
  "At a golf course",
  "At a fishing hole",
  "At a hunting cabin",
  "At a shooting range",
  "At a skeet shooting club",
  "At a rifle range",
  "At a paintball field",
  "At a skatepark",
  "At a BMX park",
  "At a bike trail",
  "At a hiking trail",
  "At a camping site",
  "At a beach",
  "At a lake",
  "At a river",
  "At a waterfall",
  "At a hot spring",
  "At a spa",
  "At a theme park",
  "At a water park",
  "At a zoo",
  "At an aquarium",
  "At a wildlife park",
  "At a science museum",
  "At an art museum",
  "At a history museum",
  "At a planetarium",
  "At an observatory",
  "At a botanical garden",
  "At an arboretum",
  "At a greenhouse",
  "At a nursery",
  "At a farmer's market",
  "At a street fair",
  "At a festival",
  "At a parade",
  "At a carnival",
  "At a county fair",
  "At a state fair",
  "At a Renaissance fair",
  "At a Halloween festival",
  "At a Christmas market",
  "At a New Year's Eve party",
  "At a Fourth of July fireworks show",
  "At a Memorial Day parade",
  "At a Labor Day festival",
  "At a Thanksgiving feast",
  "At a Christmas Eve service",
  "At a Christmas morning gift exchange",
  "At a Hanukkah celebration",
  "At a Kwanzaa celebration",
  "At a Chinese New Year celebration",
  "At a Diwali celebration",
  "At a Eid al-Fitr celebration",
  "At a Passover Seder",
  "At a Rosh Hashanah dinner",
  "At a Yom Kippur service",
  "At a Hanami party",
  "At a Cherry Blossom festival",
  "At a Mardi Gras parade",
  "At a St. Patrick's Day parade",
  "At a Cinco de Mayo celebration",
  "At a Canada Day celebration",
  "At a Australia Day celebration",
  "At a Bastille Day celebration",
  "At a Independence Day celebration",
  "At a Halloween party",
  "At a Christmas party",
  "At a New Year's party",
  "At a Valentine's Day party",
  "At a Easter egg hunt",
  "At a Mother's Day brunch",
  "At a Father's Day barbecue",
  "At a Halloween trick-or-treating",
  "At a Christmas caroling",
  "At a New Year's Eve countdown",
  "At a Valentine's Day dance",
  "At a Easter Sunday service",
  "At a Mother's Day brunch",
  "At a Father's Day barbecue"
]
